model:
  name: xgboost

data_paths:
  model: 'models/xgboost.joblib'
  test_data: 'models/xgboost_test_data.joblib'
  target_scaler: 'models/target_scaler.joblib'

data:
  split:
    test_size: .15
    eval_size: .15
  columns:
    temp: temperature_2m

hyperparams:
  sequence_models:
    lookback: 168
    forecast_horizon: 24
  forecast_horizon: 24
  lookback: 24
  model:
    n_estimators: 1000
    learning_rate: 0.025
    max_depth: 6
